removed dependency on py and updated bandit
lava-nc/lava-dnf pull request #48
Opened 2023-01-04 18:10 UTC by michaelbeale-IL

Resolved the two dependabot alerts

2023-01-05 10:32 UTC, mathisrichter approved these changes

2023-01-05 10:38 UTC, mathisrichter requested changes
There are now errors in CI.
- The new version of `bandit` is creating a problem during linting. Maybe it is incompatible with `multiprocessing`?
- lava-dnf uses `nbconvert` and `nbformat` for testing tutorials in Jupyter notebooks. Removing those dependencies is now breaking unit tests of those tutorials.

2023-01-09 09:45 UTC, mathisrichter approved these changes
Great, thanks Mike

2023-01-09 09:47 UTC, PhilippPlank approved these changes

2023-01-09 09:48 UTC, merged